import { UserRole } from '@core/enums/user-role.enum';

export const UBER_TRIPS_TABLE_EVENT_RESULT_SHOW: UserRole[] = [
  UserRole.VIEW_UBER_BRIDGE_TRIPS_EXTENDED,
  UserRole.VIEW_UBER_BRIDGE_METRICS_EXTENDED
];

export const UBER_METRIS_ENDPOINTS: UserRole[] = [
  UserRole.VIEW_UBER_BRIDGE_METRICS_EXTENDED
];

export const DEVICES_HARDFAULT_MODIFY: UserRole[] = [
  UserRole.TECH_HARDFAULT_MODIFY_ADMIN
];

export const DEVICES_HARDFAULT_DELETE: UserRole[] = [
  UserRole.TECH_HARDFAULT_DELETE_ID_ADMIN
];

export const DOCUMENTS_MONTHLY_REPORT_DELETE: UserRole[] = [
  UserRole.DEVICE_OPERATIONS_MONTHLY_REPORT_SINGLE_DELETE_ADMIN
];

export const DOCUMENTS_DAILY_REPORT_DELETE: UserRole[] = [
  UserRole.DOCS_DAILY_REPORT_DELETE_ID_ADMIN
];

export const DEVICES_LIST_STATISTICS_SHOW: UserRole[] = [
  UserRole.VIEW_TECH_DEVICE_STATISTICS
];
