export enum Api {
  CATEGORIES = '/api/category',
  CATEGORY = '/api/category/:id',
  COMMENT = '/api/comment',
  COUNTIES = '/api/county',
  COUNTY = '/api/county/:id',
  OFFERS = '/api/offer',
  OFFER_COMMENTS = '/api/offer/comments/:offerId',
  PRODUCTS = '/api/product',
  PRODUCT = '/api/product/:name',
  PRODUCT_UPDATE = '/api/product/:id',
  ROLES = '/api/role',
  ROLE = '/api/role/:id',
  SALE_POINTS = '/api/salesPoint',
  SALE_POINT_UPDATE = '/api/salesPoint/:id',
  SALE_POINT = '/api/salesPoint/:countyId',
  LOGIN = '/api/user/login',
  REGISTER = '/api/user/register',
  USER = '/api/user/:id',
  UPDATE_USER_COUNTY = '/api/user/userCounty/:userId/:countyId',
}